export const customCountries = {
    AD: { name: "Andorra" },
    AN: { name: "Anguilla" },
    AU: { name: "Australia" },
    AT: { name: "Austria" },
    BS: { name: "Bahamas" },
    BB: { name: "Barbados" },
    BE: { name: "Belgium" },
    AI: { name: "Anguilla" },
    BM: { name: "Bermuda" },
    VG: { name: "British Virgin Islands" },
    KY: { name: "Cayman Islands" },
    FK: { name: "Falkland Islands (Malvinas)" },
    GI: { name: "Gibraltar" },
    MS: { name: "Montserrat" },
    PN: { name: "Pitcairn Island" },
    SH: { name: "Saint Helena" },
    TC: { name: "Turks and Caicos Islands" },
    GB: { name: "United Kingdom" },
    BN: { name: "Brunei Darussalam" },
    BG: { name: "Bulgaria" },
    CL: { name: "Chile" },
    HR: { name: "Croatia" },
    CY: { name: "Cyprus" },
    CZ: { name: "Czech Republic" },
    DK: { name: "Denmark" },
    EE: { name: "Estonia" },
    FI: { name: "Finland" },
    FR: { name: "France" },
    DE: { name: "Germany" },
    GR: { name: "Greece" },
    HK: { name: "Hong Kong" },
    HU: { name: "Hungary" },
    IS: { name: "Iceland" },
    IE: { name: "Ireland" },
    IL: { name: "Israel" },
    IT: { name: "Italy" },
    JP: { name: "Japan" },
    KR: { name: "Republic of Korea" },
    LV: { name: "Latvia" },
    LI: { name: "Liechtenstein" },
    LT: { name: "Lithuania" },
    LU: { name: "Luxembourg" },
    MT: { name: "Malta" },
    MC: { name: "Monaco" },
    NL: { name: "Netherlands" },
    NZ: { name: "New Zealand" },
    NO: { name: "Norway" },
    PG: { name: "Papua New Guinea" },
    PL: { name: "Poland" },
    PT: { name: "Portugal" },
    RO: { name: "Romania" },
    WS: { name: "Samoa" },
    SM: { name: "San Marino" },
    SG: { name: "Singapore" },
    SK: { name: "Slovakia" },
    SI: { name: "Slovenia" },
    SB: { name: "Solomon Islands" },
    ES: { name: "Spain" },
    SE: { name: "Sweden" },
    CH: { name: "Switzerland" },
    TW: { name: "Taiwan" },
    AE: { name: "United Arab Emirates" },
  };